/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ProgrammingLanguage = {
	_id: string;
	_type: 'programmingLanguage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	date?: string;
	mainImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	description?: BlockContent;
	anecdote?: BlockContent;
	link?: string;
	paradigms?: Array<{
		name?: string;
		link?: string;
		_type: 'paradigm';
		_key: string;
	}>;
};

export type BlockContent = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
	listItem?: 'bullet';
	markDefs?: Array<{
		href?: string;
		_type: 'link';
		_key: string;
	}>;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type Post = {
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	date?: string;
	excerpt?: string;
	mainImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	body?: BlockContent;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| ProgrammingLanguage
	| BlockContent
	| SanityImageCrop
	| SanityImageHotspot
	| Slug
	| Post
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../sveltekit-app/src/lib/sanity/queries/posts.ts
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug][0]
export type PostQueryResult = {
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	date?: string;
	excerpt?: string;
	mainImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	body?: BlockContent;
} | null;
// Variable: postsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(coalesce(date, _createdAt) desc)
export type PostsQueryResult = Array<{
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	date?: string;
	excerpt?: string;
	mainImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	body?: BlockContent;
}>;

// Source: ../sveltekit-app/src/lib/sanity/queries/programmingLanguages.ts
// Variable: GET_PROGRAMMING_LANGUAGE
// Query: *[_type == "programmingLanguage" && slug.current == $slug][0]
export type GET_PROGRAMMING_LANGUAGEResult = {
	_id: string;
	_type: 'programmingLanguage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	date?: string;
	mainImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	description?: BlockContent;
	anecdote?: BlockContent;
	link?: string;
	paradigms?: Array<{
		name?: string;
		link?: string;
		_type: 'paradigm';
		_key: string;
	}>;
} | null;
// Variable: GET_PROGRAMMING_LANGUAGES
// Query: *[_type == "programmingLanguage" && defined(slug.current)] | order(coalesce(date, _createdAt) desc)
export type GET_PROGRAMMING_LANGUAGESResult = Array<{
	_id: string;
	_type: 'programmingLanguage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	date?: string;
	mainImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	description?: BlockContent;
	anecdote?: BlockContent;
	link?: string;
	paradigms?: Array<{
		name?: string;
		link?: string;
		_type: 'paradigm';
		_key: string;
	}>;
}>;
// Variable: GET_POSTS_OR_LANGS
// Query: *[_type in ["post", "programmingLanguage"] && defined(slug.current)] | order(coalesce(date, _createdAt) desc)
export type GET_POSTS_OR_LANGSResult = Array<
	| {
			_id: string;
			_type: 'post';
			_createdAt: string;
			_updatedAt: string;
			_rev: string;
			title?: string;
			slug?: Slug;
			date?: string;
			excerpt?: string;
			mainImage?: {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
			};
			body?: BlockContent;
	  }
	| {
			_id: string;
			_type: 'programmingLanguage';
			_createdAt: string;
			_updatedAt: string;
			_rev: string;
			title?: string;
			slug?: Slug;
			date?: string;
			mainImage?: {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
			};
			description?: BlockContent;
			anecdote?: BlockContent;
			link?: string;
			paradigms?: Array<{
				name?: string;
				link?: string;
				_type: 'paradigm';
				_key: string;
			}>;
	  }
>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
	interface SanityQueries {
		'*[_type == "post" && slug.current == $slug][0]': PostQueryResult;
		'*[_type == "post" && defined(slug.current)] | order(coalesce(date, _createdAt) desc)': PostsQueryResult;
		'*[_type == "programmingLanguage" && slug.current == $slug][0]': GET_PROGRAMMING_LANGUAGEResult;
		'*[_type == "programmingLanguage" && defined(slug.current)] | order(coalesce(date, _createdAt) desc)': GET_PROGRAMMING_LANGUAGESResult;
		'\n\t*[_type in ["post", "programmingLanguage"] && defined(slug.current)] | order(coalesce(date, _createdAt) desc)\n': GET_POSTS_OR_LANGSResult;
	}
}
